### ISSUE TITLE
Default Backing Store is in phase ready, but test pool cannot be used.

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-operator#1007]
### Environment info
CLI version: 5.13.0
noobaa-image: noobaa/noobaa-core:master-20220913
operator-image: noobaa/noobaa-operator:5.13.0

### Actual behavior
1. Default Backing Store is in phase ready, but test pool cannot be used.

### Expected behavior
1. Default Backing Store is in phase read and we can use test pool.

### Steps to reproduce
See in this [PR](https://github.com/noobaa/noobaa-core/pull/7142), take the changes from this commit, or use the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76). This issue is related to timing, so if every step will take a couple of minutes, it will not be reproduced (all steps must be done immediately or automatically). 
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - the steps of ‘Build images’ and ‘Deploy noobaa’.
2. I’ve noticed that after installing noobaa we need to wait before running the job, otherwise all the tests will be failed.
`kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m`
**Do not wait a couple of minutes after this condition is met, immediately move to the next step.**
3. Deploy the tests job (run it from the noobaa-core repo):
` kubectl apply -f src/test/system_tests/ceph_s3_tests/test_ceph_s3_job.yml`
4. View the logs:
`kubectl logs job/noobaa-tests-s3 -f`

### More information - Screenshots / Logs / Other output
The test pool when it will be reproduce (and all the tests will be failed):

> { name: 'noobaa-default-backing-store', resource_type: 'HOSTS', pool_node_type: 'BLOCK_STORE_FS', storage: { total: 84223205376, free: 0, used: 0, reserved: 104857600, unavailable_free: 16048295936, unavailable_used: 0, used_other: 68070051840 }, create_time: 1672658604000, io_stats: { read_count: 0, write_count: 0, read_bytes: 0, write_bytes: 0 }, data_activities: { activities: [], host_count: 0 }, nodes: { count: 1, online: 1, by_mode: { INITIALIZING: 1 } }, storage_nodes: { count: 1, online: 1, by_mode: { INITIALIZING: 1 } }, s3_nodes: { count: 0, online: 0, by_mode: {} }, hosts: { count: 1, by_mode: { INITIALIZING: 1 }, by_service: { STORAGE: 1 }, configured_count: 1 }, host_info: { volume_size: 53687091200 }, is_managed: true, undeletable: 'IN_USE', mode: 'INITIALIZING', associated_accounts: [] } 

**Describe the solution you'd like**
I would like to have an option in nb that would give the actual moment when I can use the default backing store since the solution `kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m` is not always working.

**Comment by romayalon** [comment]
@shirady 
Not sure I understand the problem, The backingstores's phase is being updated on each reconcile loop of the system, did you see a reconcile loop that should update the backingstore's phase and did it incorrectly?

**Comment by dannyzaken** [comment]
just to clarify the sequence of what Shira found:

1. noobaa is deployed using the CLI. once noobaa is ready, `noobaa install` exit. 
2. the default backing store is not ready yet. wait for the `available` condition to be met before continuing. the available condition should reflect `Ready`. see here: https://github.com/noobaa/noobaa-operator/blob/86c117be6f55f73cfe8ad6120fcb60f417933e49/pkg/backingstore/reconciler.go#L344-L353
3. wait using `kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m`
4. when `kubectl wait` is completed the backing-store is expected to be `Ready`. in the test that run right after, it looks like the pool is INITIALIZING, which should not be translated to `Ready`. see here: https://github.com/noobaa/noobaa-operator/blob/86c117be6f55f73cfe8ad6120fcb60f417933e49/pkg/backingstore/reconciler.go#L48-L51

**Comment by romayalon** [comment]
@dannyzaken yeah, i'm asking about the phase update, 
in the operator we update it on each reconcile loop, do you see modeCode (In the operator) INITIALIZING and phase was not updated to Creating?

**Comment by shirady** [comment]
Started to investigate it' I'm sharing some of the information I have:

### Logs from operator:
Here we can see that the phase is Ready and the mode is INITIALIZING.
![READY INITIALIZING2](https://user-images.githubusercontent.com/57721533/214310759-c9c3d19b-b73a-426c-8a7c-817d8ad7269a.png)

### YAML file after running `kubectl edit backingstore/noobaa-default-backing-store`
after running kubectl edit backingstore/noobaa-default-backing-store twice:
1) After `kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m` right after getting `backingstore.noobaa.io/noobaa-default-backing-store condition met`
Here we can see that the phase is Ready and the mode is INITIALIZING.
![READY INITIALIZING](https://user-images.githubusercontent.com/57721533/214311954-0fd3e2f6-b339-43b0-84aa-5348a525290b.png)


2) Run `kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m`
wait a couple of minutes after this condition is met ~3m (it's just a bypass).
You can use this command to check when the default backing store is in mode OPTIMAL:
`nb api system read_system`
Here we can see that the phase is Ready and the mode is OPTIMAL (as we expect).
![READY OPTIMAL](https://user-images.githubusercontent.com/57721533/214311984-03d8661e-9d65-4d3a-81e2-a00db067a47c.png)

We suspect that the change from phase `connecting` to `ready` is regardless of the mode.

**Comment by shirady** [comment]
We found the root cause:
in this file:
https://github.com/noobaa/noobaa-operator/blob/98e905278cf4609bf7aa278c4e260d16c3c9b5bc/pkg/backingstore/reconciler.go#L215-L229

We added some printings here to read it from the logs:
Here you can see that we are in phase Connecting and mode INITIALIZING and we change the phase to Ready (and still the mode is INITIALIZING).
![backingStore reconciler with printings](https://user-images.githubusercontent.com/57721533/214503499-18ec0be3-a261-418f-9a0e-55480b748939.png)
