### ISSUE TITLE
nb system does not response after nb uninstall with cleanup flag

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-operator#1011]
### Environment info
CLI version: 5.13.0
noobaa-image: noobaa/noobaa-core:master-20220913
operator-image: noobaa/noobaa-operator:5.13.0

### Actual behavior
1. nb system does not response  after nb uninstall with cleanup flag

### Expected behavior
1. nb system will nb uninstall + crd delete.
2. In case, this senario creates an error, throw an error with a message. 

### Steps to reproduce
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) ‘Build images’.
2. nb crd create
3. nb operator install
4. nb system create  --db-resources='{ "limits": {"cpu": "800m","memory": "1G"}, "requests": {"cpu": "800m","memory": "1G"}}' --core-resources='{ "limits": {"cpu": "500m","memory": "1G"}, "requests": {"cpu": "500m","memory": "1G"}}' --endpoint-resources='{ "limits": {"cpu": "500m","memory": "1G"}, "requests": {"cpu": "500m","memory": "1G"}}'
5. nb uninstall
6. nb uninstall --cleanup
7. y (to the question: -cleanup removes the CRDs and affecting all noobaa instances, are you sure?)
8. nb system does not response

I also reproduce it simply by:
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) ‘Build images’.
2. nb uninstall 
**works fine, prompt is back**
4. nb uninstall --cleanup 
5. y (to the question: -cleanup removes the CRDs and affecting all noobaa instances, are you sure?)
**nb does not response, prompt is not back**

### More information - Screenshots / Logs / Other output
screenshot after nb uninstall --cleanup:
![Screen Shot 2023-01-05 at 15 26 21](https://user-images.githubusercontent.com/57721533/210790565-b07a45c5-7ed9-4d3e-99b6-25d930a87020.png)
* As you can see the shell prompt is not back (even after minutes of waiting).

**Comment by shirady** [comment]
I don't know if it's related:
![Screen Shot 2023-01-05 at 15 45 03](https://user-images.githubusercontent.com/57721533/210794374-32b25741-2553-4aad-87e0-5ff7d5d17b14.png)

### Steps to reproduce
after the steps mentioned above:
1. Ctrl + C (to kill the process that was not responding)
2. make all
3. nb system list

**Comment by guymguym** [comment]
@shirady CRD deletion will hang until there are no CR instances of that CRD.
First, try to check if you have any stuck noobaa CRs in all namespaces - `kubectl get noobaa -A`.

**Comment by shirady** [comment]
I didn't succeed to reproduce it today.
I will close it, in case I'll have this issue again I'll re-open it.
