### ISSUE TITLE
Noobaa Account Status of admin@noobaa.io Prints Log with Error Message

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-operator#1043]
### Environment info
NooBaa Operator Version: 5.13.0
Platform: minikube 1.28.0

### Actual behavior
1. Show nb account status of admin@noobaa.io prints log with error message.

### Expected behavior
1. Show nb account status of admin@noobaa.io (without any error message).

### Steps to reproduce
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - ‘Build images’.
2. Based on the instruction [here](https://github.com/noobaa/noobaa-operator/blob/master/doc/noobaa-admission.md) - run the nb installation and then the make test-admission.
3. Then run: `nb account status admin@noobaa.io -n test`
_Note: `nb` is a alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._

### More information - Screenshots / Logs / Other output
I think the first line should not appear.
![Screenshot 2023-02-08 at 11 16 44](https://user-images.githubusercontent.com/57721533/217491812-38a7f07f-6f68-45c8-ad66-386b1d0bfd2a.png)

**Comment by shirady** [comment]
Initial direction: I think instead of AND operator it should be OR.
https://github.com/noobaa/noobaa-operator/blob/651a5863f58722b7629564d71254bc766f40572b/pkg/noobaaaccount/noobaaaccount.go#L358-L372

`!util.KubeCheck(noobaaAccount) || (name != “admin@noobaa.io”)`
I'll try it after I finish the current issue I'm working on.

**Comment by liranmauda** [comment]
This error come from a kubecheck that we should not do in the case of `admin@noobaa.io` 
we should change the order of the if, and in that way we can also avoid negative condition.
