### ISSUE TITLE
Is 5.13.0 released ?

### ISSUE THREAD

**Issue by Alansyf** [noobaa/noobaa-operator#1159]
### Environment info

`VERSION=$(curl -s https://api.github.com/repos/noobaa/noobaa-operator/releases/latest | jq -r '.name')
`

```
echo @VERSION 
v5.13.0
```

Then curl -LO https://github.com/noobaa/noobaa-operator/releases/download/$VERSION/noobaa-$OS-$VERSION

But latest noobaa mac CLI is 5.11.0

**Comment by nimrod-becker** [comment]
We had a technical problem with publishing the artifacts, we hope to have it all sorted out today
@utkarsh-pro
