### ISSUE TITLE
Add minKubeVersion to OLM CSV and update docs w/minimum supported Kubernetes/OpenShift versions

### ISSUE THREAD

**Issue by ron1** [noobaa/noobaa-operator#116]
The current noobaa 1.1.0 csv does not specify a minKubeVersion. In order to continue supporting Red Hat OCP 3.11 customers, I suggest that NooBaa support minKubeVersion 1.11.0 and OCP 3.11+ as long as is technically feasable. An examination of the set of OCP operator CSVs defined at https://github.com/operator-framework/community-operators/community-operators indicates almost all operators define a minKubeVersion of 1.11.0 or below. Since NooBaa downstream is a Red Hat product, it would seem to make sense for NooBaa upstream to support minKubeVersion 1.11.0 and OCP 3.11+ like Rook and other Red Hat upstream operators. Note Rook currently advertises support for Kubernetes 1.10+. It makes sense for upstream projects like NooBaa to support the broadest audience possible in order to maximize its usage.

**Comment by guymguym** [comment]
@tamireran You tested the operator on OCP 3.11 and it works well right? Any notable gaps?

**Comment by tamireran** [comment]
@guymguym no notable gaps running 2.7 on OCP 3.11

**Comment by ron1** [comment]
On AWS using Classic Load Balancer without Route 53 DNS services, I only needed to make the following changes for NooBaa to successfully operate on OCP 3.11:
- Update "Host" property for noobaa-mgmt and s3 Route resources
- Update annotation for noobaa-mgmt and s3 Service resources to use "alpha" and not "beta" in key
