### ISSUE TITLE
What is S3 Bucket Policy in Noobaa

### ISSUE THREAD

**Issue by schwienbier** [noobaa/noobaa-operator#1175]
Dear Noobaa Supports,

"S3 Bucket Policy" was mentioned several times in the github issues, e.g. https://github.com/noobaa/noobaa-operator/discussions/1173 and https://github.com/noobaa/noobaa-operator/discussions/1168. It seems we can apply the bucket policies to the buckets, where we can give bucket-access to accounts.

However, I searched for term "Bucket Policy" via https://github.com/search?q=repo%3Anoobaa%2Fnoobaa-operator+Bucket+Policy&type=code&p=3 in this repository. Few valuable CRD or documents are returned. Can you please give us a concrete example (cli/yaml) of applying the bucket policies to the buckets? Thank you in advance!

Best regards

**Comment by nimrod-becker** [comment]
The S3 Bucket Policy is set using the S3 protocol itself.

Here is a [link](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-policy.html) to the AWS CLI ref
And here is the [API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketPolicy.html) itself

**Comment by schwienbier** [comment]
understand. Thank you!
