### ISSUE TITLE
2000 reconciles every hour

### ISSUE THREAD

**Issue by vinzent** [noobaa/noobaa-operator#1282]
We have NooBaa Operator 5.13.4 on OpenShift 4.13 (part of ODF). I see that the operator logs ~2000 reconciles every hour.

I counted these loglines:

* Start BackingStore Reconcile ... 
* Start BucketClass Reconcile...
* Start NooBaa system Reconcile ...

Each of them has 1/3 of the 2000 reconciles.

If watching for example the BackingStore or BucketClass resource, I can see that the `.status.conditions[].lastHearbeatTimestmap` gets updated frequently, but nothing else. 

It seems to me, 2000 reconciles every hour - when nothing changes  - is a bit too much. 

Is this expected?

**Comment by liranmauda** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2258681

**Comment by liranmauda** [comment]
Hi Tomas,
It works as expected, we can remove the log entry if it overloads.

Please take a look at the README in the PR: https://github.com/noobaa/noobaa-operator/pull/1257

Please let us know if you have any more questions (or If the README is unclear).
