### ISSUE TITLE
Update to use operator-sdk v0.13.0 and controller-runtime v0.4.0

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#168]
https://github.com/operator-framework/operator-sdk/releases/tag/v0.13.0
https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.4.0

**Comment by jackyalbo** [comment]
Waiting for PR https://github.com/kube-object-storage/lib-bucket-provisioner/pull/185
As operator can't be complied while bucket-provisioner is using older version of k8s
