### ISSUE TITLE
CLI Command - noobaa db dump

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#169]
This can be a useful command for DB backup:
```
noobaa db dump > noobaa-db-backup.tar.gz
```

Seems like there's a native go library to do mongodump so this might be low hanging -
https://github.com/mongodb/mongo-tools

**Comment by nimrod-becker** [comment]
Maybe part of diag as well (with a flag to turn on)

**Comment by lallinger-arbeit** [comment]
Also interested in this

**Comment by jeniawhite** [comment]
Also, add a restore command
