### ISSUE TITLE
When deploying on-prem and no CephCluster exists, should skip creation of CephUser and BackingStore

### ISSUE THREAD

**Issue by nimrod-becker** [noobaa/noobaa-operator#190]
When deploying on-prem and no CephCluster exists we should skip the following steps:

- Creating CephUser
- Creating Target Bucket on RGW
- Creating Default Backing Store on top of RGW

**Comment by dannyzaken** [comment]
I rechecked it. Currently, when there is no `CephObjectStore` (the RGW resource) we skip all of the above. 

https://github.com/noobaa/noobaa-operator/blob/master/pkg/system/phase2_creating.go#L292:L304

As far as I know, there can't be a `CephObjectStore` without a `CephCluster`, so the above requirements should already be met

**Comment by guymguym** [comment]
@dannyzaken That's good, closing.
