### ISSUE TITLE
In bucket provisioner, why does the owner secret namespace default to "default"?

### ISSUE THREAD

**Issue by jeffvance** [noobaa/noobaa-operator#21]
https://github.com/noobaa/noobaa-core/blob/master/gocode/src/noobaa-s3-provisioner/cmd/noobaa-s3-provisioner.go#L158

It's arguably better to throw an error if the StorageClass bucket owner secret name and/or namespace are missing or  == "", rather than defaulting the ns. We spent some time, due to a typo in the SC, figuring out  why the owner secret was reported missing.

**Comment by dannyzaken** [comment]
not relevant anymore. rewritten provisioner code
