### ISSUE TITLE
NooBaa core gets QoS class Burstable because initContainer doesn't specify resource requests/limits.

### ISSUE THREAD

**Issue by rohantmp** [noobaa/noobaa-operator#223]

**Comment by rohantmp** [comment]
@guymguym 

The `NooBaa.Spec.CoreResources` field doesn't get propogated to the initContainer.

The condition required for QoS class Guaranteed is that the requests/limits are specified and equal to each other for all containers. Can we simply propogate this field to the initContainer as well?

**Comment by guymguym** [comment]
Hey @rohantmp 

One thing to note is that this initContainer is very small and works on the database PVC (setting file permissions), and on master we moved the DB to a separate Pod/STS -
https://github.com/noobaa/noobaa-operator/blob/master/deploy/internal/statefulset-db.yaml

So we could set very low resources for that init container.
Is that good too? 
Or is there a specific reason why it should have the same resources as the main container?

**Comment by rohantmp** [comment]
> So we could set very low resources for that init container.
That works! As long as it's requests and limits both exist and match each other.

**Comment by guymguym** [comment]
Ah got you. I thought you meant that it need to match the other container.
Matching the resources/limits is good.
Thanks
