### ISSUE TITLE
CLI add --skip-oauth flag to noobaa ui

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#248]
Which will add the ?skip-oauth to the url

**Comment by nb-ohad** [comment]
SSO cannot work as expected when using port forwarding. For that reason I think that we sould always add the skip-oauth flag when using the UI command from the CLI.
In that case, we should not add the flag at all.

**Comment by nimrod-becker** [comment]
we no longer support the ui, closing
