### ISSUE TITLE
cli doesn't show error when creating a backingstore that isn't available in the commands

### ISSUE THREAD

**Issue by kerencarmelwedel** [noobaa/noobaa-operator#274]
$ build/_output/bin/noobaa-operator-local backingstore create bubu bs
Create backing store
Available Commands:
  aws-s3               Create aws-s3 backing store
  azure-blob           Create azure-blob backing store
  google-cloud-storage Create google-cloud-storage backing store
  ibm-cos              Create ibm-cos backing store
  pv-pool              Create pv-pool backing store
  s3-compatible        Create s3-compatible backing store
Use "noobaa <command> --help" for more information about a given command.

**Comment by jeniawhite** [comment]
What did you expect to see?
It tells you the available BackingStore types.
And also sends you to `Use "noobaa --help" for more information about a given command.`

**Comment by liranmauda** [comment]
@jeniawhite 
when trying to create unsupported backingstore, An error should be prompt and not only the help.
Without an error, it makes it harder to notice if you write the backingstore name incorrectly.

**Comment by guymguym** [comment]
This is true for every subcommand that is missing.
For some reason this is not the case for thee top level commands.
Thanks for reporting, but I am unassigning from me.
