### ISSUE TITLE
CLI: `noobaa ui` trying to open wss proto instead of http

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#289]
It uses the RPC address wss://localhost:57772 instead of the UI address http://localhost:57772.
Seems to be introduced in v2.1.1

**Comment by Daornit** [comment]
any update ?

**Comment by nb-ohad** [comment]
Hi @Daornit 

The `noobaa ui` command returning a `wss` address is a bug, but let me give you some alternatives: 

The NooBaa Management Console is served by the `noobaa-mgmt` service and here are a couple of ways you can access it without the help of the `noobaa ui` comamnd, depending on your deployment:

You can use the `noobaa status` command to get a list of all available network addresses that can be used to access the mgmt service from within the cluster and from the outside. For example, running `noobaa status` on my computer, running a local minikube cluster, yields: 

```
#------------------#
#- Mgmt Addresses -#
#------------------#

ExternalDNS : []
ExternalIP  : []
NodePorts   : [https://192.168.64.61:31435]
InternalDNS : [https://noobaa-mgmt.default.svc:443]
InternalIP  : [https://10.98.238.201:443]
PodPorts    : [https://172.17.0.4:8443]

#--------------------#
#- Mgmt Credentials -#
#--------------------#

email    : admin@noobaa.io
password : *****************************
```

Usually, you should use the address under  `ExternalDNS` or `ExternalIP` to access the service but in the case that the service is not exposed via external addressing you can use the address under `NodePorts`.

**Comment by guymguym** [comment]
closing as the UI is deprecated.
