### ISSUE TITLE
deploy.go is not getting updated by `make pkg/bundle/deploy.go`

### ISSUE THREAD

**Issue by liranmauda** [noobaa/noobaa-operator#294]
`make gen` did not update the deploy.go

`make pkg/bundle/deploy.go` output was: 
make: `pkg/bundle/deploy.go' is up to date.

running manually `go run pkg/bundler/bundler.go deploy/ pkg/bundle/deploy.go` updated: 
INFO[0000] bundle files in deploy/ writing to pkg/bundle/deploy.go
INFO[0000] bundle file deploy/cluster_role.yaml size:1174 sha256:349e613915ed288629c4926e22cd42f4a3776ed38dfbc9e814a9b28211a67b3c
INFO[0000] bundle file deploy/cluster_role_binding.yaml size:267 sha256:15c78355aefdceaf577bd96b4ae949ae424a3febdc8853be0917cf89a63941fc
...
INFO[0000] bundle - done.

**Comment by guymguym** [comment]
Well makefile uses files mtime to decide.
You can override with `make gen —always-make` this is what we do in CI.
Not sure why the deps of gen target became newer...

**Comment by guymguym** [comment]
So first of all it is very easy to solve just by re-bundling every time - remove the deps of deploy.go and just make it a PHONY target that always builds, since bundling takes just few seconds anyway.

But I still wonder why this happens - here is the makefile target:
https://github.com/noobaa/noobaa-operator/blob/138f19bb1dfed15828d577565bd402515dcfc148/Makefile#L90-L92

It depends on the bundler source `pkg/bundler/bundler.go` and on any file it can find under `deploy/` folder. So I wonder - @liranmauda what is the diff in depoy.go that you get when you run it? That will help to understand why its source file mtime was not touched. 

Perhaps when git is checking out files from previous versions it restores their older mtime? if that's the case then deploy.go will have a newer mtime and will not rebuild.

**Comment by liranmauda** [comment]
`make pkg/bundle/deploy.go`:
make: `pkg/bundle/deploy.go' is up to date.

`go run pkg/bundler/bundler.go deploy/ pkg/bundle/deploy.go`:
INFO[0000] bundle files in deploy/ writing to pkg/bundle/deploy.go
INFO[0000] bundle file deploy/cluster_role.yaml size:1174 sha256:349e613915ed288629c4926e22cd42f4a3776ed38dfbc9e814a9b28211a67b3c
INFO[0000] bundle file deploy/cluster_role_binding.yaml size:267 sha256:15c78355aefdceaf577bd96b4ae949ae424a3febdc8853be0917cf89a63941fc
INFO[0000] bundle file deploy/crds/noobaa.io_backingstores_crd.yaml size:14311 sha256:b4968c3ebd9bb43bf90e2640ac2d80d95e90a059a6f92ef19eb82d2abd266bcc
INFO[0000] bundle file deploy/crds/noobaa.io_bucketclasses_crd.yaml size:7293 sha256:460cdb16739e5b43301c4ddaa005648610cdb8e29523bba39bc6a517542f0a45
INFO[0000] bundle file deploy/crds/noobaa.io_noobaas_crd.yaml size:61502 sha256:5ab2a748ff07dcabe35917561ef4eba1facaade26abcbdaf6ae05d17621bb533
INFO[0000] bundle file deploy/crds/noobaa.io_v1alpha1_backingstore_cr.yaml size:249 sha256:776deb11e769c67bf993ec77762b5375e36607bd4026e4ef20642fde2bd5dc80
INFO[0000] bundle file deploy/crds/noobaa.io_v1alpha1_bucketclass_cr.yaml size:171 sha256:af1411669ca0b29bdb7836e9e1fc44a0ddb7d4a994266abbae793a7116f6499f
INFO[0000] bundle file deploy/crds/noobaa.io_v1alpha1_noobaa_cr.yaml size:104 sha256:0e1f573b02ad8f9f1e4e8bed5fe47e4651040277e0accf1e30b1369745371483
INFO[0000] bundle file deploy/internal/ceph-objectstore-user.yaml size:148 sha256:9b60853f585d771e484854e34fc59adf56a6edb6acb1315eb2ea02b59d213755
INFO[0000] bundle file deploy/internal/cloud_creds_aws_cr.yaml size:625 sha256:8e4159bc3470c135b611b6d9f4338612be0e6ea381d5061cc79e84a7eec0ab6a
INFO[0000] bundle file deploy/internal/configmap-empty.yaml size:76 sha256:6405c531c6522ecd54808f5cb531c1001b9ad01a73917427c523a92be44f348f
INFO[0000] bundle file deploy/internal/deployment-endpoint.yaml size:2582 sha256:047a0e1625c3d166bde7792f818db7a412b4fac6d1ee37f75c9f5f4f2618cae9
INFO[0000] bundle file deploy/internal/hpa-endpoint.yaml size:283 sha256:5f6d756b2a8a7419b0d3b103c0289e911cba08748da2d36db0c0c7e497e6f423
INFO[0000] bundle file deploy/internal/prometheus-rules.yaml size:4448 sha256:31412ea08c2c489c6cccdb28acdc1817f7ed97b9f3672b1abf80ab4f4129c39f
INFO[0000] bundle file deploy/internal/route-mgmt.yaml size:262 sha256:52dacfdd2f8f4ddfe56948573ae69277096d971c9274f9afb1046871ed7f9c28
INFO[0000] bundle file deploy/internal/route-s3.yaml size:242 sha256:e5d832cf3912c648ab4b799ded80a70eaec9fc13d6181726d934af99f71a6686
INFO[0000] bundle file deploy/internal/secret-empty.yaml size:86 sha256:d63aaeaf7f9c7c1421fcc138ee2f31d2461de0dec2f68120bc9cce367d4d4186
INFO[0000] bundle file deploy/internal/service-db.yaml size:391 sha256:64559363daddd9caf781f104b876b33fb63e4f2551570e73bdb2bfae736f33ee
INFO[0000] bundle file deploy/internal/service-mgmt.yaml size:636 sha256:3449be462a77ea7e66c529308cbd86fd1c3d18685aa4649aa05514303f23908a
INFO[0000] bundle file deploy/internal/service-monitor.yaml size:235 sha256:224b1ce993c390fa80898dedfee8380f2d0209d3702eb0b8b514dd380ade453c
INFO[0000] bundle file deploy/internal/service-s3.yaml size:477 sha256:49fa69db96f9e06ac46874ec42d1a3bd81cfc7b159d75e2a2870d1f16708eafc
INFO[0000] bundle file deploy/internal/statefulset-core.yaml size:2896 sha256:a30bceca14204013e94623f8ce7855febeafeff018a65cf0b019b698fd397184
INFO[0000] bundle file deploy/internal/statefulset-db.yaml size:1555 sha256:5916e76021db87d379658147871643bfa6e0f016a53e63afefac36ea9cbe62e3
INFO[0000] bundle file deploy/internal/text/system_status_readme_progress.tmpl size:555 sha256:d26aa1028e4a235018cc46e00392d3209d3e09e8320f3692be6346a9cfdf289a
INFO[0000] bundle file deploy/internal/text/system_status_readme_ready.tmpl size:1198 sha256:ed4077141304bbf69b08401f314b70c381523c60a7e18211576ba5275a286c30
INFO[0000] bundle file deploy/internal/text/system_status_readme_rejected.tmpl size:506 sha256:32d46b0a1eadbe10501b2b3a6529503c76c0c77e25464f56f4ee9fd9115100c4
INFO[0000] bundle file deploy/namespace.yaml size:110 sha256:303398323535d7f8229cb1a5378ad019cf4fa7930891688e3eea55c77e7bf69a
INFO[0000] bundle file deploy/obc/lib-bucket-provisioner.package.yaml size:130 sha256:26eed5792ad7e75fa7e02329e648efff0be25f33595dcc1b4671fb99758f7cc0
INFO[0000] bundle file deploy/obc/lib-bucket-provisioner.v1.0.0.clusterserviceversion.yaml size:173351 sha256:aee3bfbb7be1965fbe6ec0741802d84fc81f3b47ea213c1c8bb1bb2c3eb130b6
INFO[0000] bundle file deploy/obc/objectbucket.io_objectbucketclaims_crd.yaml size:3284 sha256:edc3d10012249f73a226cca91830ae8b2751bcc10b41735db5a4a0f535e3ecb7
INFO[0000] bundle file deploy/obc/objectbucket.io_objectbuckets_crd.yaml size:4387 sha256:57432d2fe37757af1fe1e263e2426abd2e9b5afcbaf48eee543f94e2d30626ff
INFO[0000] bundle file deploy/obc/objectbucket_v1alpha1_objectbucket_cr.yaml size:378 sha256:0246e12a1337b2f68d408ff688b55fd6116bc7cd8f877e06d36e00d7255a81f9
INFO[0000] bundle file deploy/obc/objectbucket_v1alpha1_objectbucketclaim_cr.yaml size:204 sha256:1a4391ac6d7393a2d3fba47f18c1097506a3f1f27bf6309c18897e30de9ec8c8
INFO[0000] bundle file deploy/obc/storage_class.yaml size:140 sha256:9d03664a6263d8e54a00cdd604cc3cb6b5ce04ff9d73187b7fcb122bcbbdd1d2
INFO[0000] bundle file deploy/olm/catalog-source.yaml size:190 sha256:7e8580ab7a46eac1f975cc8b77010e065a7b9e516fba18eb1486d790de7aa6d5
INFO[0000] bundle file deploy/olm/csv-config.yaml size:58 sha256:7902c00f83ed852ecb10b9ba2602e5c0271fc4f94afdc81dc757198942c63217
INFO[0000] bundle file deploy/olm/description.md size:3485 sha256:e821fdae5dc993ff1bf79e6393aa965ba9d2d9488462e47ebe2daff6bb83bf2e
INFO[0000] bundle file deploy/olm/noobaa-operator.clusterserviceversion.yaml size:1577 sha256:c4ac0d890eb913d6c9e13d3dea7d403a5a17b24999f1f6bab223006789976985
INFO[0000] bundle file deploy/olm/noobaa_icon.base64 size:24048 sha256:4684eb3f4be354c728e210364a7e5e6806b68acb945b6e129ebc4d75fd97073c
INFO[0000] bundle file deploy/olm/operator-group.yaml size:155 sha256:6a81a348f305328e33cea2dd4fa6b16581995c323b8cd2e8c698fdecabe750bb
INFO[0000] bundle file deploy/olm/operator-source.yaml size:264 sha256:2f5cc3b1bec5332087fd6f3b80f0769c404a513d061ef822604fb87b6f301f30
INFO[0000] bundle file deploy/olm/operator-subscription.yaml size:237 sha256:77611fd0b8ec510d277f3f9cb7eb7f8845f2b0fda04732bf9111887d2855d7d3
INFO[0000] bundle file deploy/operator.yaml size:823 sha256:3030f31026433e2737957a3f153739ce3d1a69cf11813d27b4fd95e7452ee3df
INFO[0000] bundle file deploy/role.yaml size:1535 sha256:d1077c7d48590e7889015b59f4d5f6069f11ca8099c2ed0814e80b4a5936833f
INFO[0000] bundle file deploy/role_binding.yaml size:211 sha256:59a2627156ed3db9cd1a4d9c47e8c1044279c65e84d79c525e51274329cb16ff
INFO[0000] bundle file deploy/service_account.yaml size:250 sha256:7c68e5bd65c614787d7d4cdf80db8c14d9159ce8e940c5134d33d21dbe66893f
INFO[0000] bundle - done.

**Comment by guymguym** [comment]
So the only diff is the version file :)
Need to add it to the dependencies in the makefile like this:
```
pkg/bundle/deploy.go: pkg/bundler/bundler.go version/version.go $(shell find deploy/ -type f)
```
