### ISSUE TITLE
make requires a valid kubeconfig

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#325]
CC @obnoxxx

If we stop minikube make results in:
```
$ make
go mod tidy
go mod vendor
✅ vendor
✅ gen
build/_tools/operator-sdk-v0.17.0 run --local --operator-flags "version"
Error: error getting kubeconfig and default namespace: invalid configuration: no configuration has been provided
Usage:
  operator-sdk run [flags]
...
make: *** [Makefile:42: cli] Error 1
```

This happens because we use `operator-sdk run --local --operator-flags "version"` to build just the CLI - see here:
https://github.com/noobaa/noobaa-operator/blob/1cf4cbabde9a6ab4024421054e8ee5e48735b704/Makefile#L41-L44

We could have called `go build ...` directly but preferred to have operator-sdk call the go build in the same manner it always does. Perhaps this was changed with newer operator-sdk that it now looks for kubeconfig on its own.

However an actual running cluster is not required - it works even if I just use this valid temp kubeconfig:
```
$ export KUBECONFIG=empty-kubeconfig

$ cat empty-kubeconfig
apiVersion: v1
kind: Config
preferences: {}
current-context: temp
clusters:
- name: temp
  cluster:
    server: temp
users:
- name: temp
contexts:
- name: temp
  context:
    cluster: temp
    user: temp
    namespace: temp

$ make cli
checking operator-sdk version
operator-sdk version | grep -q "\"v0.16.0\", commit: \"55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd\""
✅ operator-sdk
go mod tidy
go mod vendor
✅ vendor
✅ gen
operator-sdk run --local --operator-flags "version"
INFO[0000] Running the operator locally in namespace temp.
INFO[0000] CLI version: 2.3.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.4.0-rc1
INFO[0000] operator-image: noobaa/noobaa-operator:2.3.0
✅ cli
```

so we might want to ask operator-sdk to provide a command to just build the binary of the operator instead of our make cli calling operator-sdk run to achieve that, or find another way to avoid this failure when no valid kubeconfig is available during build.

**Comment by obnoxxx** [comment]
@guymguym - thanks for capturing our discussion here!

If this empty kubeconfig is sufficient (and correct) to do the build, we could just add it to the `devenv.sh` script and thereby remove the dependency to minikube running.
