### ISSUE TITLE
Deleted or missing pods in pv-pool should be (re)created and keep existing PVCs

### ISSUE THREAD

**Issue by jackyalbo** [noobaa/noobaa-operator#364]
Currently when a used accidently delete a pvpool pod - we will stop the deletion with the finalizer,
But no more handling will be being made.
We need to handle such scenario better 
- creating missing pods will first try to connect to an existing pvcs
- maybe revert the deletion in some way

**Comment by guymguym** [comment]
I don't think we need to revert the pod deletion in any way. 
Just recreate it if needed by the pv-pool spec.
The pod probably doesn't even need a finalizer, only the PVCs do.
