### ISSUE TITLE
Prometheus error in operator logs

### ISSUE THREAD

**Issue by pranavgaikwad** [noobaa/noobaa-operator#41]
This is not a blocking issue. But the operator logs are filled with following error message.

```
E0827 21:14:48.945652       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to watch *v1.PrometheusRule: unknown (get prometheusrules.monitoring.coreos.com)
```
It makes it difficult to debug the operator as logs fill the screen very quickly.  

Version : 
- OpenShift 4.1.0
- NooBaa Operator v1.1.0 (installed using CLI)

**Comment by guymguym** [comment]
I also saw this.
Not sure what we do that is causing the operator to try watching on PrometheusRule repeatedly...

**Comment by guymguym** [comment]
Maybe if I replace this error to panic I will be able to catch the called...
