### ISSUE TITLE
Load custom user env from a fixed name configmap

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#426]
Since a lot of customizations are passed into the containers as env variables, 
we want to allow the user (noobaa admin) to persist some environment settings in a configmap and the noobaa containers will load.

**Comment by dannyzaken** [comment]
@kfir-payne started to take a look at this issue, and we wanted to clear some things.

currently a lot of the envs we have are derived from the setup (envs such as mongo\postgers envs, oauth), so for sure we don't want to store these in the configmap.

other envs are already stored on the CR (dbType, debugLevel). out of these, I think that `debugLevel` should move to the configmap as well. dbType should remain part of noobaa cr. @liranmauda WDYT?

**Comment by dannyzaken** [comment]
this is the full list of envs we pass to different components:
```
MONGODB_URL: “mongodb://noobaa-db-0.noobaa-db/nbcore”
POSTGRES_HOST: “noobaa-db-pg-0.noobaa-db-pg”
POSTGRES_DBNAME: nbcore
POSTGRES_USER: “”
POSTGRES_PASSWORD: “”
DB_TYPE: postgres
CONTAINER_PLATFORM: KUBERNETES
NOOBAA_LOG_LEVEL: “0”
NOOBAA_DISABLE_COMPRESSION: “false”
NOOBAA_ROOT_SECRET: “”
AGENT_PROFILE: VALUE_AGENT_PROFILE
DISABLE_DEV_RANDOM_SEED: “true”
OAUTH_AUTHORIZATION_ENDPOINT: “”
OAUTH_TOKEN_ENDPOINT: “”```

out of these I think we should support for now 
```
NOOBAA_LOG_LEVEL
DISABLE_DEV_RANDOM_SEED
NOOBAA_DISABLE_COMPRESSION
```

**Comment by liranmauda** [comment]
> other envs are already stored on the CR (dbType, debugLevel). out of these, I think that `debugLevel` should move to the configmap as well. dbType should remain part of noobaa cr. @liranmauda WDYT?

As long as It will affect both `statefulset.apps/noobaa-core` and `deployment.apps/noobaa-endpoint` and will be easy to change (manually or update via the CLI), We are ok.

**Comment by dannyzaken** [comment]
@kfir-payne you can divide it into 2 tasks. 
first, just create the CM with `DISABLE_DEV_RANDOM_SEED` and `NOOBAA_DISABLE_COMPRESSION`. 
once you have that working the second step is to move `debugLevel` to the CM as well.

AFAIK pods are not restarted automatically on configmap changes, so we will also need to handle that

**Comment by kfir-payne** [comment]
@dannyzaken sounds good, I'll start work on it.

**Comment by kfir-payne** [comment]
While working on this issue a few questions/thoughts came up, could use you opinion on them:

1. for now, the above env vars are loaded to noobaa-core through a config map. any updates to the that config map would require a pod restart (to load a new env var for example). do we want to support that?

2. do we want to use one config map for both noobaa-core and noobaa-endpoint? if so, let them both have all the env vars from the config? or handle which belong to the core and which belong to the endpoint?

3. we should decide which of the endpoint env vars we want to move to the config map.

**Comment by kfir-payne** [comment]
this is the list of env we pass to the endpoint:
    env:
      - name: MGMT_ADDR
      - name: BG_ADDR
      - name: MD_ADDR
      - name: HOSTED_AGENTS_ADDR
      - name: DB_TYPE
      - name: MONGODB_URL
      - name: POSTGRES_HOST
      - name: POSTGRES_DBNAME
        value: nbcore
      - name: POSTGRES_USER
      - name: POSTGRES_PASSWORD
      - name: VIRTUAL_HOSTS
      - name: REGION
      - name: ENDPOINT_GROUP_ID
      - name: LOCAL_MD_SERVER
      - name: LOCAL_N2N_AGENT
      - name: JWT_SECRET
      - name: NOOBAA_ROOT_SECRET
      - name: NOOBAA_LOG_LEVEL
        value: "0"
      - name: NOOBAA_DISABLE_COMPRESSION
        value: "false"

**Comment by dannyzaken** [comment]
1. I think that we do want to react to changes in the configmap. don't have a good idea how to do that. 

2. I think we can use a single CM

@guymguym @nimrod-becker WDYT?

**Comment by kfir-payne** [comment]
because we are using the same config map for the core and for the endpoint, they both would have the same env vars, and any changes to the config map will trigger a restart in both of them.
It will also mean that any same name env var would have to be with the same value.
