### ISSUE TITLE
Feature Request: Allow custom pod templates

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-operator#455]
As discussed yesterday in the community meeting we would like to set custom annotations to the noobaa-endpoint pods for our logging solution via the NooBaa CR. Also it would probably be best to allow customization of all the pod templates (core, db, endpoint) via the NooBaa CR.

**Comment by snorwin** [comment]
+1

**Comment by liranmauda** [comment]
Hi @lallinger-arbeit 
Can you please test If after PR #719 we can close this issue?

**Comment by snorwin** [comment]
I did some test in our env and it works as expected with the latest operator version `master-20210912`.

**Comment by lallinger-arbeit** [comment]
hi @liranmauda,
unfortunateley i current don't have any time to validate this and probably won't have until at least end of october..

**Comment by liranmauda** [comment]
> hi @liranmauda,
> unfortunateley i currently don't have any time to validate this and probably won't have until at least end of october..

Sure, so as @snorwin tested it I will close this issue, and if we will need to add/change anything we can reopen (or open another issue).
