### ISSUE TITLE
Added govcloud regions to valid AWSRegions

### ISSUE THREAD

**Issue by edcrosbys** [noobaa/noobaa-operator#535]
AWSRegions currently does not have govcloud regions listed.

**Comment by edcrosbys** [comment]
Will need to change arn strings in /deploy/internal/cloud_creds_aws_cr.yaml
and /pkg/system/phase2_creating.go to detect if govcloud or aws.

**Comment by edcrosbys** [comment]
Logs from Nooba:
`time="2021-02-04T16:07:13Z" level=info msg="❌ Not Found: BackingStore \"noobaa-default-backing-store\"\n"
time="2021-02-04T16:07:13Z" level=info msg="CredentialsRequest \"noobaa-aws-cloud-creds\" created. Creating default backing store on AWS objectstore" func=ReconcileDefaultBackingStore sys=openshift-storage/noobaa
time="2021-02-04T16:07:13Z" level=info msg="❌ Not Found: \"noobaa-aws-cloud-creds-secret\"\n"
time="2021-02-04T16:07:13Z" level=info msg="Secret \"noobaa-aws-cloud-creds-secret\" was not created yet by cloud-credentials operator. retry on next reconcile.." sys=openshift-storage/noobaa
time="2021-02-04T16:07:13Z" level=info msg="SetPhase: temporary error during phase \"Configuring\"" sys=openshift-storage/noobaa
time="2021-02-04T16:07:13Z" level=warning msg="⏳ Temporary Error: cloud credentials secret \"noobaa-aws-cloud-creds-secret\" is not ready yet" sys=openshift-storage/noobaa
time="2021-02-04T16:07:13Z" level=info msg="UpdateStatus: Done generation 1" sys=openshift-storage/noobaa`
Logs from credential operator:
`time="2021-02-04T18:02:50Z" level=error msg="error syncing creds in mint-mode" actuator=aws cr=openshift-storage/noobaa-aws-cloud-creds error="AWS Error: MalformedPolicyDocument: Partition \"aws\" is not valid for resource \"arn:aws:s3:::nb.<snip>.apps.ocp4.<snip>.gov\".\n\tstatus code: 400, request id: de22fe50-05a2-4f81-b2e8-930233ea51c1"
time="2021-02-04T18:02:50Z" level=error msg="error syncing credentials: error syncing creds in mint-mode: AWS Error: MalformedPolicyDocument: Partition \"aws\" is not valid for resource`

**Comment by radikaled** [comment]
For reference regarding Amazon Resource Names (ARNs) in GovCloud (US) Regions:

https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html

**Comment by dannyzaken** [comment]
@edcrosbys I created PR #536 to fix this issue. 
I don't have access to a cluster in GovCloud. If you have a system in GovCloud I would appreciate it if you can test it.  Let me know if you need any help with testing it using an upstream image

**Comment by usrbinkat** [comment]
Successful test of PR https://github.com/noobaa/noobaa-operator/pull/536 on ocp 4.7 govcloud `us-gov-west-1` airgap cluster.
