### ISSUE TITLE
Operator not starting when /etc/passwd is not editable

### ISSUE THREAD

**Issue by mdundek** [noobaa/noobaa-operator#555]
### Environment info
- NooBaa Operator Version: 5.6.0
- Platform: Kubernetes 1.18.10

### Actual behavior
1. When installing Noobaa with the CLI on a OS that does not permit appending the noobaa operator user to the file /etc/passwd, the pod never starts and prints the log `/etc/passwd: permission denied` error

### Expected behavior
1. Noobaa operator pod starts as expected

### More information - Screenshots / Logs / Other output
The problem has been solved with the help of Guy on Slack, by changing the ENTRYPOINT of the operator Docker image to `CMD [/usr/local/bin/noobaa-operator, "operator", "run"] ` rather than the startup script that appends the noobaa user directly to `/etc/passwd`. This script seems to have become obsolete anyway.

![noobaa2](https://user-images.githubusercontent.com/12046522/108773535-cb1d4200-755e-11eb-96ec-2c797431b03e.png)
![noobaa3](https://user-images.githubusercontent.com/12046522/108773541-cc4e6f00-755e-11eb-90ab-a468eae9dfba.png)

**Comment by guymguym** [comment]
@dannyzaken Can you suggest a PR to fix according to the new suggested operator-sdk scaffold?

**Comment by mdundek** [comment]
Done, PR name `issue-555`.
