### ISSUE TITLE
Brew install failed

### ISSUE THREAD

**Issue by VadimDez** [noobaa/noobaa-operator#564]
### Environment info
- Mac OS 10.15.6

### Actual behavior
1. Install using brew:
```
brew install noobaa/noobaa/noobaa
```
2. Fails with:
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "noobaa"
Download failed: https://homebrew.bintray.com/bottles-noobaa/noobaa-5.6.0.mojave.bottle.tar.gz
```

### Expected behavior
1. to install noobaa correctly

### Steps to reproduce
1. install using brew

**Comment by guymguym** [comment]
@dannyzaken FYI. 
@VadimDez BTW maybe best move this issue to https://github.com/noobaa/homebrew-noobaa

**Comment by guymguym** [comment]
I assume we can close this issue by now. @VadimDez please reopen if this is still a problem.
