### ISSUE TITLE
Connect CLI to existing Noobaa instance

### ISSUE THREAD

**Issue by tommyhargroves** [noobaa/noobaa-operator#572]
Is there documentation to connect the Noobaa CLI to an existing instance? Noobaa was provisioned when installing the OpenShift Container Storage Operator, I have access to the UI but not the CLI.

**Comment by guymguym** [comment]
Hi @tommyhargroves 
The CLI loads kubeconfig just like kubectl/oc so once you configure it to use your cluster correctly, and you can see the noobaa CR using `kubectl get noobaa -n <namespace>` then you can use the noobaa cli with `noobaa status -n <namespace>` or any other cli command.
Let me know if this helps.

**Comment by tommyhargroves** [comment]
Hi @guymguym thank you for your help. That helps my understanding. I've been looking for documentation on how to connect it to my cluster correctly so that it can see my existing noobaa CR, as I do not want to run the "install" command and have it deploy the operator and a whole new system. I have version 5.6.0 as well. Thank you

**Comment by guymguym** [comment]
@tommyhargroves Sure. Let us know if you need further help. Closing this issue for now.
