### ISSUE TITLE
nsfs: Unable to list contents of Noobaa buckets created under /nsfs by S3 tool

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-operator#573]
OCP Cluster:

```
[root@ocp-akshat-inf akshat]# oc version
Client Version: 4.5.24
Server Version: 4.6.17
Kubernetes Version: v1.19.0+e405995
```

Noobaa version:

```
[root@ocp-akshat-inf akshat]# ./noobaa-linux-master-20210215 status 
INFO[0000] CLI version: 5.7.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210215 
INFO[0000] operator-image: noobaa/noobaa-operator:master-20210215 
INFO[0000] noobaa-db-image: centos/mongodb-36-centos7   
INFO[0000] Namespace: noobaa         
```

When I am installing Noobaa code, except backingstore pod, all pods come up. This is getting tracked in [defect 530](https://github.com/noobaa/noobaa-operator/issues/530)

```
[root@ocp-akshat-inf akshat]# oc get pod -n noobaa
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          8d
noobaa-db-0                                        1/1     Running       1          8d
noobaa-default-backing-store-noobaa-pod-e59431c2   0/1     Terminating   0          24h
noobaa-endpoint-6d87469b9f-qx2gd                   1/1     Running       1          7d19h
noobaa-operator-64b6f86868-nffcl                   1/1     Running       0          8d
```

Using s3 compatibility tool, created following buckets:
```
[root@hpo-node1 s3-tests]# s3 ls
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ocp-akshat-inf'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-03-09 23:16:17 akshat-ty7mv9yniq9dj43co7jzpl-1   --> New bucket
2021-03-09 23:16:17 akshat-ty7mv9yniq9dj43co7jzpl-2   --> New bucket
2021-03-09 23:16:17 bucket-new
2021-03-09 23:16:17 guy-bucket
2021-03-09 23:16:17 nsfs-200-500
2021-03-09 23:16:17 first.bucket
2021-03-09 23:16:17 nsfs
```
When I try listing on them, it fails:
```
[root@hpo-node1 s3-tests]# s3 ls s3://akshat-ty7mv9yniq9dj43co7jzpl-1
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ocp-akshat-inf'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ocp-akshat-inf'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ocp-akshat-inf'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 2): We encountered an internal error. Please try again.
```

From the endpoint log:
`16759 ^[[32mMar-10 7:12:42.424^[[35m [Endpoint/13] ^[[31m[ERROR]^[[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidDigest</Code><Message>The Conten      t-MD5 you specified is not valid.</Message><Resource>/akshat-ty7mv9yniq9dj43co7jzpl-1/foo</Resource><RequestId>km33uoqe-91422w-12pw</RequestId></Error> PUT /akshat-ty7mv9yniq9dj43co7jzpl-1/fo      o {"host":"ocp-akshat-inf:8443","accept-encoding":"identity","user-agent":"Boto3/1.17.18 Python/3.6.8 Linux/4.18.0-240.15.1.el8_3.x86_64 Botocore/1.20.18","content-md5":"YWJyYWNhZGFicmE=","ex      pect":"100-continue","x-amz-date":"20210310T071242Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=6IUhji5FNL3rn6Eafrj0/20210310/us-east-1/s3/aws4_req      uest, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=4b18603c1ddabf67906d63f8ac180e74c23664a1306d7a3c4339e394763be65b","content-length":"3"} Error: The Content-MD5       you specified is not valid.`

```
16777 ^[[32mMar-10 7:16:30.976^[[35m [Endpoint/13] ^[[31m[ERROR]^[[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encount      ered an internal error. Please try again.</Message><Resource>/akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&amp;prefix=&amp;delimiter=%2F&amp;encoding-type=url</Resource><RequestId>km33zl1y-yu7      en-4tf</RequestId></Error> GET /akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&prefix=&delimiter=%2F&encoding-type=url {"host":"ocp-akshat-inf:8443","accept-encoding":"identity","user-agent":"aw      s-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.15.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.ls","x-amz-date":"20210310T071630Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb9      2427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=6IUhji5FNL3rn6Eafrj0/20210310/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, S      ignature=8154345e7321b4db6d6adc1e4b05f8e386fce0ef2b55728aa0f269cad057344d"} Error: ENOENT: no such file or directory, mkdir '/nsfs/akshat-ty7mv9yniq9dj43co7jzpl-1'
16778 ^[[32mMar-10 7:16:31.874^[[35m [Endpoint/13] ^[[31m[ERROR]^[[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encount      ered an internal error. Please try again.</Message><Resource>/akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&amp;prefix=&amp;delimiter=%2F&amp;encoding-type=url</Resource><RequestId>km33zlrp-gap      u3l-ofq</RequestId></Error> GET /akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&prefix=&delimiter=%2F&encoding-type=url {"host":"ocp-akshat-inf:8443","accept-encoding":"identity","user-agent":"a      ws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.15.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.ls","x-amz-date":"20210310T071631Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb      92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=6IUhji5FNL3rn6Eafrj0/20210310/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,       Signature=570e7d9c883ea32bde3a3f9cf5944776f741f0f6ae29b7bff1aa24623cc56ebe"} Error: ENOENT: no such file or directory, mkdir '/nsfs/akshat-ty7mv9yniq9dj43co7jzpl-1'
16779 ^[[32mMar-10 7:16:32.152^[[35m [Endpoint/13] ^[[31m[ERROR]^[[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encount      ered an internal error. Please try again.</Message><Resource>/akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&amp;prefix=&amp;delimiter=%2F&amp;encoding-type=url</Resource><RequestId>km33zlzh-4dx      eb8-12ds</RequestId></Error> GET /akshat-ty7mv9yniq9dj43co7jzpl-1?list-type=2&prefix=&delimiter=%2F&encoding-type=url {"host":"ocp-akshat-inf:8443","accept-encoding":"identity","user-agent":"      aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.15.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.ls","x-amz-date":"20210310T071632Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996f      b92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=6IUhji5FNL3rn6Eafrj0/20210310/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date,       Signature=fa300430989eb6fb8336731e25abb5431a86cc0bf57898fa0cd28689a4416a44"} Error: ENOENT: no such file or directory, mkdir '/nsfs/akshat-ty7mv9yniq9dj43co7jzpl-1'
```

When I create a bucket manually, I am able to list its content well. 

```
[root@hpo-node1 s3-tests]# s3 ls s3://bucket-new
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ocp-akshat-inf'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-03-08 23:09:45         16 new1
```
To enable this listing of manually created buckets, @guymguym helped doing chown command on the backend directory. 

Need help in attempting listing of buckets through the tool as well. The S3 tool fails all tests with this error:

```
======================================================================
ERROR: test suite for <module 's3tests_boto3.functional.test_headers' from '/root/s3-tests/s3tests_boto3/functional/test_headers.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/nose/suite.py", line 229, in run
    self.tearDown()
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/nose/suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/nose/suite.py", line 368, in teardownContext
    try_run(context, names)
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/root/s3-tests/s3tests_boto3/functional/__init__.py", line 224, in teardown
    nuke_prefixed_buckets(prefix=prefix)
  File "/root/s3-tests/s3tests_boto3/functional/__init__.py", line 119, in nuke_prefixed_buckets
    objects_list = get_objects_list(bucket_name, client)
  File "/root/s3-tests/s3tests_boto3/functional/__init__.py", line 65, in get_objects_list
    response = client.list_objects(Bucket=bucket)
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/s3-tests/virtualenv/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the ListObjects operation (reached max retries: 4): We encountered an internal error. Please try again.
```

**Comment by akmithal** [comment]
@nimrod-becker , Please help getting its resolution. @guymguym helped us for listing content manually. He might have good context on how to fix it for the tool usage as well. Thanks

**Comment by akmithal** [comment]
[endpoint_log_10_march.zip](https://github.com/noobaa/noobaa-operator/files/6114252/endpoint_log_10_march.zip)

**Comment by guymguym** [comment]
@akmithal I believe that the bas md5 error is unrelated to your issue, because the s3-tests has such a negative test to verify that the endpoint can detect bad content-md5.

So the error that you have is on list-objects:
```
Error: ENOENT: no such file or directory, mkdir '/nsfs/akshat-ty7mv9yniq9dj43co7jzpl-1'
```

Please provide some more info on the mount point in the endpoint:
```
POD=noobaa-endpoint-XXX
kubectl exec $POD -- id
kubectl exec $POD -- ls -l /nsfs
kubectl exec $POD -- ls -l /
```

We saw that there is a permission issue for the mount point even when we chmod 777 on the dir, and we suggested to check either updating the openshift SCC or verify with the CSI driver/filesystem why this permission is not working. I think this issue requires some more investigation before we can do anything with it on the operator level, so I suggest to work on this offline to find the root cause. Thanks

**Comment by akmithal** [comment]
[root@ocp-akshat-inf ~]# POD=noobaa-endpoint-6d87469b9f-qx2gd

[root@ocp-akshat-inf ~]# kubectl exec $POD -- id
uid=1000610000(noob) gid=0(root) groups=0(root),1000610000

[root@ocp-akshat-inf ~]# kubectl exec $POD -- ls -l /nsfs
total 59
drwxr-xr-x. 2 noob root 4096 Mar  9 11:21 0nishant-4ztzn605u5hkx126m86hp-foo
drwxr-xr-x. 2 root root 4096 Mar  9 10:56 akshat-1
drwxr-xr-x. 2 noob root 4096 Mar  9 11:21 anishant-4ztzn605u5hkx126m86hp-foo
drwxr-xr-x. 2 noob root 4096 Mar  8 12:44 bucket-1001
drwxr-xr-x. 3 noob root 4096 Mar  9 07:09 bucket-new
drwxr-xr-x. 3 noob root 4096 Mar  8 12:42 guy-bucket
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-1
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-10
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-11
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-12
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-13
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-14
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-15
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-16
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-17
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-18
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-19
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-2
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-26
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-27
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-28
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-29
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-3
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-30
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-31
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-32
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-33
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-34
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-35
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-36
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-37
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-38
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-39
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-4
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-40
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-43
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-44
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-45
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-46
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-47
drwxr-xr-x. 3 noob root 4096 Mar  9 11:20 nishant-4ztzn605u5hkx126m86hp-48
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-64
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-65
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-66
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-67
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-68
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-69
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-70
drwxr-xr-x. 2 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-72
drwxr-xr-x. 3 noob root 4096 Mar  9 11:21 nishant-4ztzn605u5hkx126m86hp-73
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-qnsgwes9zm10vcyy0ha5m-1
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-qnsgwes9zm10vcyy0ha5m-2
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-qnsgwes9zm10vcyy0ha5m-3
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-qnsgwes9zm10vcyy0ha5m-5
drwxr-xr-x. 2 noob root 4096 Mar  9 11:20 nishant-qnsgwes9zm10vcyy0ha5m-6
drwxrwxrwx. 9 noob root 4096 Mar  9 11:20 nsfs
drwxr-xr-x. 2 noob root 4096 Mar  8 12:35 nsfs-200-500
drwxr-xr-x. 3 noob root 4096 Mar  8 12:38 test
drwxr-xr-x. 2 noob root 4096 Mar  9 11:57 test-1

[root@ocp-akshat-inf ~]# kubectl exec $POD -- ls -l /
total 5
lrwxrwxrwx.   1 root root    7 Nov  3 15:22 bin -> usr/bin
drwxrwxr-x.   1 root root    6 Feb 15 08:13 data
drwxr-xr-x.   5 root root  360 Mar  2 18:56 dev
drwxrwxr-x.   1 root root   56 Mar  2 18:56 etc
drwxr-xr-x.   1 root root   18 Feb 15 08:13 home
-rwxr-xr-x.   1 root root  655 Feb 15 08:06 install_nodejs.sh
lrwxrwxrwx.   1 root root    7 Nov  3 15:22 lib -> usr/lib
lrwxrwxrwx.   1 root root    9 Nov  3 15:22 lib64 -> usr/lib64
drwxrwxr-x.   1 root root   49 Feb 15 08:13 log
drwx------.   2 root root    6 Dec  4 17:37 lost+found
drwxr-xr-x.   2 root root    6 Nov  3 15:22 media
drwxr-xr-x.   2 root root    6 Nov  3 15:22 mnt
drwxrwxr-x.   1 root root   27 Feb 15 08:13 noobaa_init_files
drwxrwxrwx.  61 noob root 4096 Mar  9 11:57 nsfs
drwxr-xr-x.   2 root root    6 Nov  3 15:22 opt
dr-xr-xr-x. 390 root root    0 Mar  2 18:56 proc
dr-xr-x---.   1 root root   26 Feb 15 08:13 root
drwxr-xr-x.   1 root root   21 Mar  2 18:56 run
lrwxrwxrwx.   1 root root    8 Nov  3 15:22 sbin -> usr/sbin
drwxr-xr-x.   3 root root   20 Feb 15 08:13 src
drwxr-xr-x.   2 root root    6 Nov  3 15:22 srv
dr-xr-xr-x.  13 root root    0 Feb 26 11:12 sys
drwxrwxrwt.   1 root root    6 Mar 10 07:22 tmp
drwxr-xr-x.   1 root root   19 Dec  4 17:37 usr
drwxr-xr-x.   1 root root   28 Dec  4 17:37 var
[root@ocp-akshat-inf ~]# 

Sure, let me discuss with CSI development team about this as well.

**Comment by guymguym** [comment]
I wonder why `nishant-XX` dirs were created ok but `akshat-XX` did not...
Can you speculate what is the change between those setups?

**Comment by akmithal** [comment]
Yes, I am raising another bug for this problem as well. What we found is, 
1. s3 from app server reports few buckets "akshat-{random}" which are not present from /nsfs
2. /nsfs has few buckets "nishant-{random}" which have been manually deleted from app server using s3 command. They are not visible in "s3 ls" view as well.

**Comment by akmithal** [comment]
https://github.com/noobaa/noobaa-core/issues/6407 is raised by Casandra to track this - https://github.com/noobaa/noobaa-operator/issues/573#issuecomment-795151469

**Comment by dannyzaken** [comment]
@akmithal @guymguym, sorry for the late handling of this issue. I'll be happy to sync with you regarding it

**Comment by nimrod-becker** [comment]
@akmithal is this still relevant with the latest builds?

**Comment by akmithal** [comment]
I think we can close this bug since we have moved onto user account related buckets and objects upload and since then, I haven't found problem in this region. Thanks
