### ISSUE TITLE
Noobaa endpoints jump to ready even when db is not ready

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-operator#602]
### Environment info
- NooBaa Operator Version: master+e528d54d3fda6133cdbd30e1465f2c6ffe9388e7
- Platform: OKD 4.5

### Actual behavior
1. When the db pod is not ready endpoints still jump to ready but then throw errors, that the db is not reachable.

### Expected behavior
1. Endpoints report ready state only when the connection to the db is successful

### Steps to reproduce
1. Delete all pods (`oc delete pods --all`) or scale the db to 0 and restart the endpoints
2. If the startup of the db takes longer than the startup of the endpoints, endpoints will report ready and throw errors that the db is unreachable

### More information - Screenshots / Logs / Other output
(only seen with MongoDB but i suspect that it happens with PostgreSQL too)
(stumbled across this issue while using this workaround: #481)

**Comment by guymguym** [comment]
We would expect a ready-probe set for the endpoints so at least on startup it will wait for the DB connection.

It won't be needed to keep probing this as the endpoints already run, even if connection is lost (we do have a timeout in place that will eventually kill the container if we loose DB connection ~30 minutes).

**Comment by lallinger-arbeit** [comment]
@liranmauda this is a minor issue. I will close it, but you may reopen it
