### ISSUE TITLE
Latest version is not available with go get github.com/noobaa/noobaa-operator.

### ISSUE THREAD

**Issue by VolkerKozlowski** [noobaa/noobaa-operator#625]
### Environment info

- NooBaa Operator Version: 5.7.0

### Actual behavior

When I 

> go get github.com/noobaa/noobaa-operator/v2

I ll get  version 2.3.0. 

> go get github.com/noobaa/noobaa-operator

noobaa-operator@v1.2.0

### Expected behavior

I ll expect latest Version (today it is 5. -something)

### Steps to reproduce
go get github.com/noobaa/noobaa-operator
or
or go get github.com/noobaa/noobaa-operator/v2

**Comment by guymguym** [comment]
Hey @VolkerKozlowski 
CC @dannyzaken - Check this out.
When we updated our module version to 2.3.0 we had to update all of the golang imports to /v2.
So perhaps now with the 5.x.x versions we need to use /v5?
