### ISSUE TITLE
Noobaa account_api - update_account should allow updating default_resource for the account

### ISSUE THREAD

**Issue by nilesh-bhosale** [noobaa/noobaa-operator#652]
### Environment info
NooBaa Version: VERSION
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210607
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

Platform: Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify
Server Version: 4.7.12
Kubernetes Version: v1.20.0+df9c838

### Actual behavior
1. update_account method does not allow changing `default_resource` for an existing S3 account
Ref: https://github.com/noobaa/noobaa-core/blob/master/src/api/account_api.js#L166

### Expected behavior
1. update_account method should allow changing `default_resource` for an existing S3 account

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
Updating datapath related config (like can an account create new buckets, what's its default resource and its allowed_buckets) is done using the following API
```account.update_account_s3_access```

**Comment by nilesh-bhosale** [comment]
In that case, can we enhance to allow `account.update_account_s3_access` updating `new_buckets_path`? which is a datapath setting.
I am trying to do 1 Noobaa RPC call (`account.update_account_s3_access` OR `account.update_account`) instead of 2 (`account.update_account_s3_access` AND `account.update_account`) to update the base dir (Namespace resource + new_buckets_path) for the s3 accounts we create.

**Comment by nimrod-becker** [comment]
@romayalon WDYT? makes sense?
@nilesh-bhosale if we change it would move, so the API would change

**Comment by romayalon** [comment]
@nimrod-becker 
moving only `new_buckets_path` from `account.update_account` to `account.update_account_s3_access` is a bit weird,
the result of it is that we update uid and gid in `account.update_account` and `new_buckets_path` in `account.update_account_s3_access` which is not good.
I would say move nothing and do 2 calls, or we move the whole nsfs_account_config update to `account.update_account_s3_access`.

**Comment by nimrod-becker** [comment]
@romayalon true.
I think the desire it to separate between an account's general config and S3/IO and Access config.
Since uid and gid are affecting and related to access (just like allowed_buckets in a sense) maybe we should move all the three
WDYT?

@nilesh-bhosale Romy is correct, if anything we would move all 3, WDYT?

**Comment by nilesh-bhosale** [comment]
@nimrod-becker , I am fine moving all three params in the `nsfs_account_config` to `account.update_account_s3_access` if that makes sense. We anyway are not allowing updates to uid/gid and so mainly interested in updating `default_resource` and `new_buckets_path` for an existing account.
