### ISSUE TITLE
noobaa namespacestore list is not updated when resource is deleted via pool_api/delete_namespace_resource

### ISSUE THREAD

**Issue by bssrikanth** [noobaa/noobaa-operator#669]
### Environment info
INFO[0000] CLI version: 5.9.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210622 
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0 

Platform: OC: 4.7.12

### Actual behavior
noobaa namespacestore list continues to show the resource which was deleted using pool_api delete_namespace_resource API call.

### Expected behavior
DB/object list which noobaa namespacestore list refers should be updated/deleted when resource is deleted using pool_api delete_namespace_resource API call.

### Steps to reproduce
1. Create namespacestore 'fs1', read the properties via `noobaa API` as well as `noobaa namespacestore` command
# noobaa api pool_api read_namespace_resource '{"name": "fs1"}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.read_namespace_resource() Request: map[name:fs1] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:39529/rpc/ 0xc00003b0e0 
INFO[0001] RPC: Connecting websocket (0xc00003b0e0) &{RPC:0xc000499090 Address:wss://localhost:39529/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc00003b0e0) &{RPC:0xc000499090 Address:wss://localhost:39529/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: pool.read_namespace_resource() Response OK: took 0.3ms 
fs_backend: GPFS
fs_root_path: /nsfs/fs1
mode: OPTIMAL
name: fs1

# noobaa namespacestore list
I0623 06:59:06.309268  558915 request.go:645] Throttling request took 1.017016968s, request: GET:https://api.hpoocpci.cp.fyre.ibm.com:6443/apis/node.k8s.io/v1beta1?timeout=32s
NAME   TYPE   TARGET-BUCKET   PHASE   AGE        
fs1    nsfs                   Ready   3h23m30s

2. Delete the namespacestore via `Noobaa API`:
   
# noobaa api pool_api delete_namespace_resource '{"name": "fs1"}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.delete_namespace_resource() Request: map[name:fs1] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:39417/rpc/ 0xc000e340a0 
INFO[0001] RPC: Connecting websocket (0xc000e340a0) &{RPC:0xc0004670e0 Address:wss://localhost:39417/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000e340a0) &{RPC:0xc0004670e0 Address:wss://localhost:39417/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: pool.delete_namespace_resource() Response OK: took 49.7ms 
null

3. Check noobaa namespacestore list, it still lists namespacestore `fs1`:

# noobaa namespacestore list
NAME   TYPE   TARGET-BUCKET   PHASE   AGE       
fs1    nsfs                   Ready   3h24m5s 

4. Try reading the properties of `fs` via `Noobaa_api`, it actually returns error:
  
# noobaa api pool_api read_namespace_resource '{"name": "fs1"}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.read_namespace_resource() Request: map[name:fs1] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33839/rpc/ 0xc0009fb860 
INFO[0001] RPC: Connecting websocket (0xc0009fb860) &{RPC:0xc0005b4910 Address:wss://localhost:33839/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc0009fb860) &{RPC:0xc0005b4910 Address:wss://localhost:33839/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
ERRO[0001] ⚠️  RPC: pool.read_namespace_resource() Response Error: Code=NO_SUCH_NAMESPACE_RESOURCE Message=No such namespace resource: fs1 
FATA[0001] ❌ No such namespace resource: fs1            

5. Try deleting namespacestore via noobaa cli, it as well complains that resource does not exists but it deletes NamespaceStore object entry, i think in DB?

# noobaa namespacestore delete fs1
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.read_namespace_resource() Request: {Name:fs1} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33301/rpc/ 0xc000c14af0 
INFO[0001] RPC: Connecting websocket (0xc000c14af0) &{RPC:0xc000559090 Address:wss://localhost:33301/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000c14af0) &{RPC:0xc000559090 Address:wss://localhost:33301/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
ERRO[0001] ⚠️  RPC: pool.read_namespace_resource() Response Error: Code=NO_SUCH_NAMESPACE_RESOURCE Message=No such namespace resource: fs1 
INFO[0001] 🗑️  Deleting: NamespaceStore "fs1"           
INFO[0002] 🗑️  Deleted : NamespaceStore "fs1"           
# noobaa namespacestore list
No namespace stores found.

**Comment by nimrod-becker** [comment]
When you list the namespacestores, you are referring to listing those CRDs or using the API to list all the pools?

If you are talking about the CRDs, the namespacestores. Then you should be using the k8s API (which is deleting a namespacestore) if you want that reflects, going via the RPC won't sync the k8s entities

**Comment by bssrikanth** [comment]
Ok. Got the point. Thank you.

**Comment by nimrod-becker** [comment]
hi @bssrikanth why did we reopen this ?

**Comment by nilesh-bhosale** [comment]
Hi @nimrod-becker , would the pool_api - create_namespace_resource won't create a Noobaa namespace store resource CR ?

**Comment by nimrod-becker** [comment]
calling the RPC itself ? no it won't create the namespace store CRD equivalent
