### ISSUE TITLE
for NS buckets, instead of showing 0 0 number of objects, show N/A or something similar

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-operator#671]
### Environment info
- NooBaa Operator Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

oc version
Client Version: 4.7.8
Server Version: 4.7.8
Kubernetes Version: v1.20.0+7d0a2b2

noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210609
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

 noobaa status
INFO[0001] CLI version: 5.9.0
INFO[0001] noobaa-image: noobaa/noobaa-core:master-20210609
INFO[0001] operator-image: noobaa/noobaa-operator:master-20210609
INFO[0001] noobaa-db-image: centos/postgresql-12-centos7
INFO[0001] Namespace: noobaa

### Actual behavior
1.

s3u4 ls s3://test4dir
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.17.113.231'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-06-23 00:50:04     108624 date
noobaa bucket status test4dir
INFO[0001] :white_check_mark: Exists: NooBaa "noobaa"
INFO[0001] :white_check_mark: Exists: Service "noobaa-mgmt"
INFO[0001] :white_check_mark: Exists: Secret "noobaa-operator"
INFO[0001] :white_check_mark: Exists: Secret "noobaa-admin"
INFO[0001] :airplane:  RPC: bucket.read_bucket() Request: {Name:test4dir}
WARN[0001] RPC: GetConnection creating connection to wss://localhost:45101/rpc/ 0xc000ca0960
INFO[0001] RPC: Connecting websocket (0xc000ca0960) &{RPC:0xc00041c730 Address:wss://localhost:45101/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc000ca0960) &{RPC:0xc00041c730 Address:wss://localhost:45101/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] :white_check_mark: RPC: bucket.read_bucket() Response OK: took 4.4ms
Bucket status:
  Bucket                 : test4dir
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : 0  --> **why does it say 0 ?**
  Data Size              : 0.000 B
  Data Size Reduced      : 0.000 B
  Data Space Avail       : 0.000 B
endpoint
ls -lrt test4dir
total 112
-rw-r-----. 1 5004 5004 108624 Jun 23 07:50 date
Storage cluster
 ls -lrt test4dir/
total 112
-rw-r-----. 1 5004 5004 108624 Jun 23 00:50 date

### Expected behavior
1.

Get the correct display of number of objects on the noobaa  cli 

### Steps to reproduce
1.

**Comment by nimrod-becker** [comment]
Namespace buckets don't have the capabilities to show the number of objects. Unlike regular bucket where we keep MD within the DB and can query and get this number, for NS it would require continuous scanning of the underlying storage, which is not really desirable.

**Comment by rkomandu** [comment]
Discussed with @guymguym and opened this defect as per slack channel discussion

**Comment by nimrod-becker** [comment]
I'm changing the title of the issue, since the discussion was about changing the output of the CLI and not counting the objects on a NS bucket

**Comment by rkomandu** [comment]
Neha checked today 

noobaa bucket status buck-2
INFO[0001] :white_check_mark: Exists: NooBaa "noobaa"
INFO[0001] :white_check_mark: Exists: Service "noobaa-mgmt"
INFO[0001] :white_check_mark: Exists: Secret "noobaa-operator"
INFO[0001] :white_check_mark: Exists: Secret "noobaa-admin"
INFO[0001] :airplane:  RPC: bucket.read_bucket() Request: {Name:buck-2}
WARN[0001] RPC: GetConnection creating connection to wss://localhost:41025/rpc/ 0xc0001972c0
INFO[0001] RPC: Connecting websocket (0xc0001972c0) &{RPC:0xc000100be0 Address:wss://localhost:41025/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0001972c0) &{RPC:0xc000100be0 Address:wss://localhost:41025/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] :white_check_mark: RPC: bucket.read_bucket() Response OK: took 23.7ms
Bucket status:
  Bucket                 : buck-2
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : N/A
  Data Size              : N/A
  Data Size Reduced      : N/A
  Data Space Avail       : N/A

noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210627
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

Thank you for this fix @nimrod-becker @guymguym
