### ISSUE TITLE
Feature Request: Tunable to prevent creation of default backingstore and default bucketclass

### ISSUE THREAD

**Issue by troppens** [noobaa/noobaa-operator#690]
Feature request:

NooBaa operator creates default `backingstore` and default `bucketclass`:
```
# oc get backingstore,bucketclass
NAME                                                  TYPE      PHASE      AGE
backingstore.noobaa.io/noobaa-default-backing-store   pv-pool   Rejected   13h

NAME                                                PLACEMENT                                                        NAMESPACEPOLICY   PHASE      AGE
bucketclass.noobaa.io/noobaa-default-bucket-class   {"tiers":[{"backingStores":["noobaa-default-backing-store"]}]}                     Rejected   13h
#
```

To build an NS-FS based solution, I want to bring-up NooBaa without default `backingstore` and default `bucketclass`. To do so I would require a tunable in the NooBaa CR which prevents the creation of those default resources.

**Comment by dannyzaken** [comment]
should be handled with this PR - https://github.com/noobaa/noobaa-operator/pull/1002

The change adds a flag to noobaa CR `ManualDefaultBackingStore`. with this flag set, the operator does not reconcile the default backingstore and it can be deleted. 
This does not effect the default bucket class, which can be modified to any desired policy

Closing this issue. @troppens, let us know if there are any issues with this solution.

**Comment by nimrod-becker** [comment]
@madhuthorat  @rkomandu
Please note that with this fix, we enable the das operator to switch the default BS to an NS FS one.
There's still work to be done on the das operator side to perform this action during HPO Deployment

**Comment by rkomandu** [comment]
@nimrod-becker , 
-- what type of action,needs to be performed from HPO deployment side, will check with @madhuthorat on this 

Secondly, when the PR is merged, could you tell me which ODF it is coming through (4.13?)

**Comment by nimrod-becker** [comment]
The NS FS Namespace store is already being created as part of the deployment.
The only thing missing is to set that NSStore as the default resource for NooBaa.

Code exists on the 4.13 branch.
