### ISSUE TITLE
Fix Topic Tag for OpenShift

### ISSUE THREAD

**Issue by slammajamma28** [noobaa/noobaa-operator#698]
I notice you have a topic tag of `openshif`... obviously that should be `openshift`.

**Comment by guymguym** [comment]
@slammajamma28 Where?

**Comment by slammajamma28** [comment]
I'm sorry I wasn't clear. I meant in the GitHub topic tags. [See here](
https://i.imgur.com/dIyzAEU.png).

**Comment by guymguym** [comment]
@slammajamma28 Ah! Thanks you. Fixed 👍
