### ISSUE TITLE
Operator pod state goes into CrashLoopBackOff state

### ISSUE THREAD

**Issue by kfir-payne** [noobaa/noobaa-operator#712]
### Environment info
- NooBaa Operator Version: master-20210808
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Operator pod state goes into CrashLoopBackOff state.

### Expected behavior
1 .Operator pod state should remain running.

### Steps to reproduce
1. upgrade an existing system to that version of the operator.

### More information - Screenshots / Logs / Other output

[must-gather-0908-1.tar.gz](https://github.com/noobaa/noobaa-operator/files/6966595/must-gather-0908-1.tar.gz)

from the logs it looks like the operator is trying to assign a value to a non-initialised map, this is happing when we try to set up a value to the Annotation filed at the core pod.

**Comment by liranmauda** [comment]
Related to https://github.com/noobaa/noobaa-core/issues/6603

**Comment by bssrikanth** [comment]
I hit the operator issue which is fixed in PR #713. I am using latest dockerhub build which is 0810. Would this fix be available in next build?

**Comment by liranmauda** [comment]
Hi @bssrikanth 
The build you are using is `master-20210810`.
This issue was fixed today (20210811) so the next build would contain it.
