### ISSUE TITLE
Operator Pod getting restarted multiple times

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-operator#714]
Environment info
NooBaa Version: master-20210809
Platform: OCP 4.7.13

Actual behavior
Operator Pod getting restarted again and again

Steps to reproduce
Installed above noobaa version build
```
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          18h
noobaa-db-pg-0                                     1/1     Running       0          18h
noobaa-default-backing-store-noobaa-pod-6026f1ed   0/1     Terminating   0          15h
noobaa-endpoint-5b5c576d8d-8thjn                   1/1     Running       0          6h8m
noobaa-operator-7567f4cd79-bwg8m                   1/1     Running       18         18h
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210809
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

[root@api.ns.cp.fyre.ibm.com ~]# oc get nodes
NAME                         STATUS   ROLES           AGE   VERSION
master0.ns.cp.fyre.ibm.com   Ready    master,worker   23h   v1.20.0+df9c838
master1.ns.cp.fyre.ibm.com   Ready    master,worker   23h   v1.20.0+df9c838
master2.ns.cp.fyre.ibm.com   Ready    master,worker   23h   v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]#
```

Logs:
[log.tar.gz](https://github.com/noobaa/noobaa-core/files/6968025/log.tar.gz)

**Comment by liranmauda** [comment]
Hi @nehasharma5 

`KubeGet` is getting this error:  `etcdserver: request timed out` which is unexpected, and it panics.

- Can you describe what was done in this cluster? 
- Do you still have this system running?
- Is this issue easily reproduced (I have tried to reproduce it but did not succeed).

**Comment by nehasharma5** [comment]
@liranmauda I did nothing , I am on 15 Aug build , getting this continuously even on ideal setup. For me it is easily reproducible

**Comment by liranmauda** [comment]
@nehasharma5 
- what is the output of `kubectl get pods -A | grep etc`? 
- Are you reusing a cluster or doing a fresh install of the OCP?

**Comment by nehasharma5** [comment]
@liranmauda 
[root@api.ns.cp.fyre.ibm.com ~]# kubectl get pods -A | grep etc
openshift-etcd-operator                            etcd-operator-664db986fb-j8f9p                            1/1     Running       9          2d1h
openshift-etcd                                     etcd-master0.ns.cp.fyre.ibm.com                           3/3     Running       0          7d19h
openshift-etcd                                     etcd-master1.ns.cp.fyre.ibm.com                           3/3     Running       0          7d19h
openshift-etcd                                     etcd-master2.ns.cp.fyre.ibm.com                           3/3     Running       0          7d19h
openshift-etcd                                     etcd-quorum-guard-6cc7f5954d-8j87q                        1/1     Running       0          2d1h
openshift-etcd                                     etcd-quorum-guard-6cc7f5954d-g2dss                        1/1     Running       0          2d1h
openshift-etcd                                     etcd-quorum-guard-6cc7f5954d-w2btr                        1/1     Running       0          7d17h
openshift-etcd                                     revision-pruner-3-master0.ns.cp.fyre.ibm.com              0/1     Completed     0          7d17h
openshift-etcd                                     revision-pruner-3-master1.ns.cp.fyre.ibm.com              0/1     Completed     0          7d17h
openshift-etcd                                     revision-pruner-3-master2.ns.cp.fyre.ibm.com              0/1     Completed     0          7d17h
[root@api.ns.cp.fyre.ibm.com ~]#

[root@api.ns.cp.fyre.ibm.com ~]# kubectl get nodes
NAME                         STATUS   ROLES           AGE     VERSION
master0.ns.cp.fyre.ibm.com   Ready    master,worker   7d19h   v1.20.0+df9c838
master1.ns.cp.fyre.ibm.com   Ready    master,worker   7d19h   v1.20.0+df9c838
master2.ns.cp.fyre.ibm.com   Ready    master,worker   7d19h   v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]#

I am reusing ocp cluster

**Comment by liranmauda** [comment]
Wierd, I was expecting the etcd not to be ready...
- Is this still happening? 
- Is this happens on a fresh new OCP? 

By the look of it, It is related to the OCP, and I don't see what we can do here. 
We want this panic to accrue, as the OCP is not playing nicely 🙂 

When we have this kind of error, an error that we are not expecting, we cannot handle, the desired outcome is to panic and restart the pod.  

In a case that the OCP/K8s is returning a persistent error that we can't handle, the pod will keep getting panic and keep restarting.

**Comment by nehasharma5** [comment]
Yes, this is still happening . I created a new cluster around 7 days back on this also I am facing same issue

**Comment by liranmauda** [comment]
@nehasharma5 please attach the latest operator logs + the previous one.

**Comment by nehasharma5** [comment]
@liranmauda Please find attached logs
[op_pr_18.log](https://github.com/noobaa/noobaa-operator/files/7006142/op_pr_18.log)
[op_18.log](https://github.com/noobaa/noobaa-operator/files/7006143/op_18.log)

**Comment by ketankhurana64** [comment]
[root@api.osculate.cp.fyre.ibm.com ~]# oc get pod -n openshift-etcd
NAME                                                 READY   STATUS      RESTARTS   AGE
etcd-master0.osculate.cp.fyre.ibm.com                4/4     Running     4          43h
etcd-master1.osculate.cp.fyre.ibm.com                4/4     Running     4          43h
etcd-master2.osculate.cp.fyre.ibm.com                4/4     Running     4          43h
etcd-quorum-guard-6c9cd66bc5-4b296                   1/1     Running     0          42h
etcd-quorum-guard-6c9cd66bc5-f8vmc                   1/1     Running     0          42h
etcd-quorum-guard-6c9cd66bc5-wvm8p                   1/1     Running     0          42h
revision-pruner-6-master0.osculate.cp.fyre.ibm.com   0/1     Completed   0          42h
revision-pruner-6-master1.osculate.cp.fyre.ibm.com   0/1     Completed   0          42h
revision-pruner-6-master2.osculate.cp.fyre.ibm.com   0/1     Completed   0          42h

**Comment by ketankhurana64** [comment]
events pertaining to describing pod etcd-master0.osculate.cp.fyre.ibm.com

```Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Warning  Unhealthy  16m   kubelet  Readiness probe failed: + unset ETCDCTL_ENDPOINTS
+ /usr/bin/etcdctl --command-timeout=2s --dial-timeout=2s --endpoints=unixs://10.17.109.209:0 endpoint health -w json
+ grep '"health":true'
{"level":"warn","ts":"2021-08-25T09:00:35.066Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-7f845139-edfe-464e-b470-a80887aa572d/10.17.109.209:0","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: unhealthy cluster
```

**Comment by ketankhurana64** [comment]
[operator_panic.zip](https://github.com/noobaa/noobaa-operator/files/7045785/operator_panic.zip)
Attached Operator logs(with previous flag)

**Comment by nehasharma5** [comment]
New openshift installation with version 4.8.2
[must-gather.local.7913165914490915881.tar.gz](https://github.com/noobaa/noobaa-operator/files/7135021/must-gather.local.7913165914490915881.tar.gz)

**Comment by nehasharma5** [comment]
Not reproducible on baremetal
