### ISSUE TITLE
broken `go get github.com/noobaa/noobaa-operator/pkg/apis/noobaa/v1alpha1`

### ISSUE THREAD

**Issue by kaovilai** [noobaa/noobaa-operator#718]
### Environment info
```
go version
go version go1.16.6 darwin/amd64
```

### Actual behavior
1.
```
go get: github.com/noobaa/noobaa-operator@none updating to
        github.com/noobaa/noobaa-operator@v1.2.0 requires
        github.com/coreos/prometheus-operator@v0.31.1 requires
        github.com/prometheus/prometheus@v2.9.2+incompatible requires
        k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
```

### Expected behavior
1. module installed
### Steps to reproduce
1. 
```
$ go get github.com/noobaa/noobaa-operator/pkg/apis/noobaa/v1alpha1
```

### More information - Screenshots / Logs / Other output
It appears PR in https://github.com/noobaa/noobaa-operator/issues/625 did not resolve the issue permanently.

Version 5.x cannot be accessed on this page. It appears there are no tagged 5.x versions available on pkg.go.dev
https://pkg.go.dev/github.com/noobaa/noobaa-operator/pkg/apis/noobaa/v1alpha1?tab=versions

**Comment by guymguym** [comment]
Can we close this one?
