### ISSUE TITLE
Is it possible to use block storage as backing store

### ISSUE THREAD

**Issue by reesede** [noobaa/noobaa-operator#739]
I'm trying to set up Noobaa on an OpenShift cluster that uses block storage, not filesystem. Is it possible to configure Noobaa so that the backing store VolumeMode is able to use block instead of filesystem?

I was able to get past the DB using filesystem by converting a single, unused drive to filesystem, but this is not a viable option for the backing store, since I need to continue to use the cluster with block.

**Comment by guymguym** [comment]
Hi @reesede Sorry for the delayed response.
NooBaa requires a local filesystem on the volume to be used as storage.
Is there a specific issue with letting openshift set up a filesystem on the volume, or you were looking for removing the FS from the stack altogether?
