### ISSUE TITLE
Admin password logged in clear-text

### ISSUE THREAD

**Issue by snorwin** [noobaa/noobaa-operator#809]
### Environment info
- NooBaa Version:  noobaa/noobaa-core:master-20211205
- Platform: **Kubernetes v1.21.1+6438632 | OpenShift 4.8.17**

### Actual behavior
The `noobaa-operator` logs the admin password in clear-text:
```
time="2021-12-06T07:59:13Z" level=info msg="✈️  RPC: system.create_system() Request: {Name:noobaa Email:admin@noobaa.io Password:u1q/w9H7ICFVlaIL8fvq/M==}"
```

### Expected behavior
Password and other credentials in logs are obfuscated:
```
time="2021-12-06T07:59:13Z" level=info msg="✈️  RPC: system.create_system() Request: {Name:noobaa Email:admin@noobaa.io Password:*************}"
```

### Steps to reproduce
1. Create a new NooBaa CR.
2. Check the logs of the  `noobaa-operator`  pod.

**Comment by guymguym** [comment]
Thank you @snorwin ! FYI @dannyzaken

**Comment by dannyzaken** [comment]
discussed this issue with @kfir-payne. we plan to fix it by defining a new `SensitiveString` type and implementing a formatter for it. It will obfuscate the actual value when printed out, but should not affect JSON marshaling\unmarshaling

**Comment by kfir-payne** [comment]
As @dannyzaken said, a new `String()` implemented for the sensitive struct in the mentioned PR.
https://github.com/noobaa/noobaa-operator/pull/816

**Comment by kfir-payne** [comment]
Hi @snorwin, since https://github.com/noobaa/noobaa-operator/pull/816 got merged and fixed the problem I'm closing the issue :)

**Comment by snorwin** [comment]
@kfir-payne thanks a lot for fixing the issue 😃
