### ISSUE TITLE
Base the image on UBI8, not 7

### ISSUE THREAD

**Issue by mykaul** [noobaa/noobaa-operator#9]
In the Dockerfile, we use the UBI7 minimal image:
```
registry.access.redhat.com/ubi7/ubi-minimal:latest
```

We should move to using the UBI8 image.

**Comment by guymguym** [comment]
@mykaul Thanks!

I used operator-sdk which generated the dockerfile (link to master):
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/build_dockerfile.go#L37

Do you think we should check with operator-sdk why they still use ubi7?
I assume it won't make a difference for us to change though.

**Comment by mykaul** [comment]
Opened https://github.com/operator-framework/operator-sdk/issues/1656 - let's see how it goes.

**Comment by guymguym** [comment]
Watching - https://github.com/operator-framework/operator-sdk/pull/1895

**Comment by ron1** [comment]
@guymguym FYI, it appears operator-sdk 0.11+ has now upgraded to ubi8.

**Comment by guymguym** [comment]
@ron1 Right. We are still on operator-sdk 0.10 but I was testing ubi8 a bit on my local env in the past week and now pushing a PR to use ubi8.
