### ISSUE TITLE
Implement BackingStore type pv-pool in Operator CR & CLI

### ISSUE THREAD

**Issue by ron1** [noobaa/noobaa-operator#91]
According to the noobaa-operator reconciliation code here: https://github.com/noobaa/noobaa-operator/blob/be83b8fe0467bded6c5ee9dea59853808cc01170/pkg/backingstore/reconciler.go#L512, the noobaa-operator does not yet support BackingStore type "pv-pool". This is a blocker for many folks that want a performant NooBaa deployment on Kubernetes using their own storage.

At a minimum, the BackingStore documentation available here: https://github.com/noobaa/noobaa-operator/blob/master/doc/backing-store-crd.md#pvc-type should be updated to reflect that this feature has not yet been implemented. In addition, consider elevating the priority of this issue in the NooBaa backlog.

**Comment by tamireran** [comment]
@ron1 You are correct. We will add it to the CLI soon. In the meantime, you can use the web management console from your browser. The access details can be found with the command 
`noobaa status` or `kubectl describe noobaa`
Once you are in, you will see a button "Add Storage Resources". Click on it, and click on "Deploy Kubernetes Pool" in the new window. You will see a little wizard that will get you a local storage on local PV. 
Please let us know if you have any issues.

**Comment by ron1** [comment]
@tamireran Thanks for the clarification. I did not realize NooBaa Core supported this feature and that the limitation is just in the Operator and CLI.

Am I correct that pv-pools work with all Kubernetes/OpenShift dynamically-provisioned volumes and not just Kubernetes 1.14 GA Local Persistent Volumes? Based on the reference to "local storage on local PV" in your comment, this is not quite clear.

**Comment by tamireran** [comment]
@ron1, correct. We support Kubernetes/OpenShift dynamically-provisioned
volumes

**Comment by ron1** [comment]
@tamireran @guymguym Unfortunately, pvpool/pvstore type storage resources created via the "Advanced pvstore create" CLI or through the Web UI cannot be referenced from BucketClass CRs, the "Manage bucketclass" CLI, and therefore from ObjectBucketClaim CRs and the "Manage obc" CLI. This essentially makes them unusable unless I am missing something. If this is the case, please elevate the priority of this issue. A patch should be fairly easy to implement since the code needed to create a pvpool BackingStore has already been implemented for the "Advanced pvstore create" CLI.

**Comment by guymguym** [comment]
@ron1 I know unfortunately. That's a hard gap. I'll try to push it.

**Comment by ron1** [comment]
@guymguym Note that I am currently working on a patch for this issue here: https://github.com/ron1/noobaa-operator/tree/issue-91-pv-pool-backing-store.

I think my patch will make the CLI "Advanced pvstore management" function obsolete. Do you agree? If so, should this patch also remove that functionality or should the removal of that functionality be accomplished via a separate issue/PR?

**Comment by guymguym** [comment]
@ron1 That's awesome! 

Yes of course the CLI actions of pvstore where just a temporary solution until this was handled properly using pv-pool BackingStore.

I think that it makes most sense to remove both the commands of `noobaa pvstore list/create` and `noobaa bucket list/create/delete` once we implement the generic `noobaa api *` command as suggested in #138 - what do you think?

**Comment by guymguym** [comment]
Fixed in #146
