### ISSUE TITLE
noobaa-operator looking for aws region in node name causing it to crash

### ISSUE THREAD

**Issue by bipuladh** [noobaa/noobaa-operator#92]
https://github.com/noobaa/noobaa-operator/blob/master/pkg/system/phase4_configuring.go#L208
is the root cause of the crash in v2.0.2. Node names do not have regions embedded in them(the ones I am working with). When I removed it and built an image it worked as expected. need a better way to search for region.

**Comment by guymguym** [comment]
Thanks @bipuladh !
This is the same as #90

**Comment by bipuladh** [comment]
@guymguym sorry forgot to check.

**Comment by guymguym** [comment]
no worries - this is a real blocker so I'm happy you reported quickly.

Also if I take a second to generalize here - I don't mind dup issues that much at all. In my opinion opening an issue per occurrence should be the default practice as it represents the reality of using the project and leads to faster fixes for issues that occur many times.
