### ISSUE TITLE
Replication fails

### ISSUE THREAD

**Issue by ghisl1** [noobaa/noobaa-operator#923]
### Environment info
- NooBaa Operator Version: 5.9.0-cf74fd9
- Platform: OpenShift 4.9

I created a multi-cloud environment based on ceph lab platform, a scality lab platform, a scality staging platform and a local pool

### Actual behavior
1. the replication worked properly but it systematically failed whatever the S3 back end is 
The replication is stuck on the second target . (see attachment)
I tested several buckets with different targets and the behavior is always the same
All the storage resources are up (see attachment)
### Expected behavior
1. Object must be replicated on the 2 targets resources

### Steps to reproduce
1. create a 2 targets-based replication and put an object in the noobaa-exposed bucket

### More information - Screenshots / Logs / Other output
![NooBaa_all_storage_resources_up](https://user-images.githubusercontent.com/4938686/169012851-b055317e-094c-4ded-aca7-2ee15b2e7333.png)
![NooBaa_rep-labscality-labceph_failed](https://user-images.githubusercontent.com/4938686/169012854-bdc667ed-4587-4afe-b235-0f7dcab28ca9.png)

**Comment by romayalon** [comment]
Hi @ghisl1,
This might be a bit confusing.. 
First, I'll say that NooBaa UI is deprecated and we actually removed it completely on master.
The UI replication is actually shows the mirroring feature and not the new replication feature..
Are you using mirroring/replication? 
it'll help if you can explain how you configured the replication / on which docs your configuration based

**Comment by ghisl1** [comment]
Hi @romayalon 
It' s more confusing to me.
I use mirroring in a tier (see attachment)
![Mirror](https://user-images.githubusercontent.com/4938686/169520625-62eaaa4a-f62c-4773-8eee-4bd3443d755b.png)
and
noobaa bucket status uc2-rep-labobos-labceph
 Bucket status:
  Bucket                 : uc2-rep-labobos-labceph
  Type                   : REGULAR
  Mode                   : OPTIMAL
  ResiliencyStatus       : OPTIMAL
  QuotaStatus            : QUOTA_NOT_SET
  Num Objects            : 1
  Data Size              : 587.152 KB
  Data Size Reduced      : 587.155 KB
  Data Space Avail       : 1.000 PB

2022-05-20T14:06:33+02:00" level=info msg="✈️  RPC: bucket.read_bucket() Request: {Name:uc2-rep-labobos-labceph}"
time="2022-05-20T14:06:33+02:00" level=warning msg="RPC: GetConnection creating connection to wss://localhost:58688/rpc/ 0xc000736af0"
time="2022-05-20T14:06:33+02:00" level=info msg="RPC: Connecting websocket (0xc000736af0) &{RPC:0xc0003e78b0 Address:wss://localhost:58688/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}"
time="2022-05-20T14:06:34+02:00" level=info msg="RPC: Connected websocket (0xc000736af0) &{RPC:0xc0003e78b0 Address:wss://localhost:58688/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}"
time="2022-05-20T14:06:34+02:00" level=info msg="✅ RPC: bucket.read_bucket() Response OK: took 7.8ms"

I didn't rely on a specific doc as the UI was enough explicit to fulfill my requirements
It worked good at the beginning but I got the issue  after creating a backend unavailibility (stop s3 api exposure on one of my labs (ceph))

BR
Ghislain

**Comment by romayalon** [comment]
@ghisl1 
Just to be sure, you re-enabled the s3 API exposure, right?
And can you supply logs, please? it'll help us understand what's going on there
must gather on noobaa diagnose will be good

**Comment by ghisl1** [comment]
sorry for the delay
The platform comes back to normal I don't know when and how
