### ISSUE TITLE
BackingStore types listed in CRD doc are incorrect

### ISSUE THREAD

**Issue by ron1** [noobaa/noobaa-operator#98]
The BackingStore CRD doc here: https://github.com/noobaa/noobaa-operator/blob/master/doc/backing-store-crd.md#backingstore-crd includes the following statement which has errors:

```Multiple types of backing-stores are supported: aws-s3, s3-compatible, google-cloud-storage, azure-blob, obc, pvc.```

According to the source code here: https://github.com/noobaa/noobaa-operator/blob/e648adc33e92c01e470f4e779121df134c16d69d/pkg/apis/noobaa/v1alpha1/backingstore_types.go#L103, the ```pvc``` type should be named ```pv-pool```. Furthermore, type ```obc``` does not appear to be defined currently and type ```pvc/pv-pool``` does not appear to be implemented yet.

Consider updating the BackingStore CRD doc to address this issue.

**Comment by guymguym** [comment]
Fixed in #113
