### ISSUE TITLE
Upgrade lib-bucket-provisioner version

### ISSUE THREAD

**Issue by romayalon** [noobaa/noobaa-operator#980]
### Environment info
- NooBaa Operator Version: 5.12
- Platform:  minikube 1.1.1 

At the time of Bucket replication development, I noticed a bug in lib-bucket-provisioner library (https://github.com/kube-object-storage/lib-bucket-provisioner/issues/219),
This bug also affects the Quota feature. The bug was fixed so we need to upgrade the version, the issue is that they bumped some dependencies that we need to handle as well.
 
### Actual behavior
1.

### Expected behavior
1.

### Steps to reproduce
1.

**Comment by liranmauda** [comment]
It is fixed in #1084
